sudo: required
language: cpp

env:
  global: OMP_NUM_THREADS=2 APPROXMVBB_CACHE_DIR="$HOME/ApproxMVBBCache"

cache:
  directories:
  - ${APPROXMVBB_CACHE_DIR}

matrix:
  include:
  - env: GCC_VERSION=5 
    os: linux
    dist: xenial
    addons: &gcc5
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']

  - env: GCC_VERSION=6
    os: linux
    dist: xenial
    addons: &gcc6
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']

  - env: CLANG_VERSION=7.0
    os: linux
    dist: xenial
    addons: &clang7
        apt:
          packages:
            - util-linux
            - clang-7.0
            - g++-6
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial

  - env: APPLE_CLANG="YES"
    os: osx
    osx_image: xcode9.2
    compiler: clang

  - env: APPLE_CLANG="NO"
    os: osx
    osx_image: xcode9.2
    compiler: clang

# Install dependencies
install:
  - export ROOT_PATH=`pwd`/../;
  - export CHECKOUT_PATH=`pwd`;
  - echo "ROOT_PATH= $ROOT_PATH"
  - echo "CHECKOUT_PATH= $CHECKOUT_PATH"

  - export branchName=$TRAVIS_BRANCH

  - mkdir -p $APPROXMVBB_CACHE_DIR/{bin,include,lib,share}
  - export CMAKE_PREFIX_PATH="$APPROXMVBB_CACHE_DIR;/usr/local"

  - chmod +x $CHECKOUT_PATH/travis/install_${TRAVIS_OS_NAME}.sh
  - . $CHECKOUT_PATH/travis/install_${TRAVIS_OS_NAME}.sh

script:
  - chmod +x $CHECKOUT_PATH/travis/build.sh
  - . $CHECKOUT_PATH/travis/build.sh

after_success:
  - cd $CHECKOUT_PATH
  - git reset --hard HEAD # Discard build artifacts
  - git clean -df # Discard build artifacts

notifications:
  email: false
